
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supermarket
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-supermarket:/mysql-supermarket

  web1:
    build: ./webapp
    container_name: web1
    depends_on:
      - mysql_db
    ports:
      - "8080:80"
    restart: unless-stopped

  web2:
    build: ./webapp
    container_name: web2
    depends_on:
      - mysql_db
    ports:
      - "8081:80"
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"  # Access Jenkins at localhost:9090
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home:


