version: '3.8'

services:
  web1:
    build: ./webapp
    container_name: web1
    depends_on:
      - mysql_db
    ports:
      - "8080:80"
    volumes:
      - ./webapp:/var/www/html
    restart: unless-stopped
    networks:
      - fyp_fyp_devnet

  web2:
    build: ./webapp
    container_name: web2
    depends_on:
      - mysql_db
    ports:
      - "8081:80"
    volumes:
      - ./webapp:/var/www/html
    restart: unless-stopped
    networks:
      - fyp_fyp_devnet

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - fyp_fyp_devnet

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-with-sonar-and-docker
    container_name: jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - fyp_fyp_devnet

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JAVA_OPTS=-Xmx2048m -Xms1024m 
      - sonar.web.javaAdditionalOpts=-Djava.security.egd=file:/dev/./urandom
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonarpass
    volumes:
      - fyp_sonarqube_data:/opt/sonarqube/data
    depends_on:
      - postgres
    networks:
      - fyp_fyp_devnet

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpass
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fyp_fyp_devnet

volumes:
  jenkins_home:
  mysql_data:
  postgres_data:
  fyp_sonarqube_data:

networks:
  fyp_fyp_devnet:
    external: true
 
 




