FROM jenkins/jenkins:lts

USER root

# Install Docker CLI and Java
RUN apt-get update && \
    apt-get install -y docker.io openjdk-17-jdk && \
    apt-get clean

# Add Jenkins user to Docker group
RUN usermod -aG docker jenkins

USER jenkins


