version: "3.8"
 
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supermarket
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-supermarket:/mysql-supermarket
    networks:
      - devnet
 
  web1:
    build: ./webapp
    container_name: web1
    depends_on:
      - mysql_db
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - devnet
 
  web2:
    build: ./webapp
    container_name: web2
    depends_on:
      - mysql_db
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - devnet
 
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-with-sonar-and-docker
    container_name: jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - devnet
 
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - devnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql_db
    networks:
      - devnet
 
    
 
volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
 
networks:
  devnet:
    driver: bridge
 
 




